config/routes.rb
Rails.application.routes.draw do
  get 'admins/index'
  devise_for :members
  get 'sessions/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'members#index'

  resources :cohorts
  resources :courses
  resources :instructors
  resources :students
  resources :admins 
  resources :members           
end

app/models/admin.rb
class Admin < ApplicationRecord      
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cohort.rb
class Cohort < ApplicationRecord
    has_many :students
    belongs_to :instructor, optional: true
    belongs_to :course, optional: true

    default_scope { order(:id) }
end

app/models/course.rb
class Course < ApplicationRecord
    has_many :cohorts

    default_scope { order(:id) }
end

app/models/instructor.rb
class Instructor < ApplicationRecord
    has_many :cohorts

    default_scope { order(:id) }
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/student.rb
class Student < ApplicationRecord
    belongs_to :cohort, optional: true

    default_scope { order(:id) }
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
    before_action :authenticate_member!
    #Links to my /admin route
    #links to a /views/admin/index.html.erb
    def index
        @admin = Admin.all
    end

    #Links to my  /admin/:id route
    #links to a views/admin/show.html.erb
    def show
        @admin = Admin.find(params[:id])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cohorts_controller.rb
class CohortsController < ApplicationController
    before_action :authenticate_member!
    
    def index
        @cohorts = Cohort.all
    end

    def show
        @cohort = Cohort.find(params[:id])
    end


    def new
        @cohort = Cohort.new
    end

    def create
        @cohort = Cohort.create(cohort_params)
        redirect_to '/cohorts'
    end


    def edit
        @cohort = Cohort.find(params[:id])
    end

    def update
        @cohort = Cohort.find(params[:id])
        @cohort.update(cohort_params)
        redirect_to '/cohorts'
    end


    def destroy
        Cohort.find(params[:id]).destroy
        redirect_to '/cohorts'
    end

    private

    def cohort_params
        params.require(:cohort).permit(:name, :start_date, :end_date, :course_id, :instructor_id)
    end

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
    before_action :authenticate_member!
    #Links to my /courses route
    #links to a /views/courses/index.html.erb
    def index
        @courses = Course.all
    end

    #Links to my /courses/:id route
    #links to a views/courses/show.html.erb
    def show
        @course = Course.find(params[:id])
    end


    def new
        @course = Course.new
    end

    def create
        @course = Course.create(course_params)
        redirect_to '/courses'
    end


    def edit
        @course = Course.find(params[:id])
    end

    def update
        @course = Course.find(params[:id])
        @course.update(course_params)
        redirect_to '/courses'
    end

    def destroy
        Course.find(params[:id]).destroy
        redirect_to '/courses'
    end

    private

    def course_params
        params.require(:course).permit(:course_name)
    end

end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController
    before_action :authenticate_member!
    #Links to my /instructors route
    #links to a /views/instructors/index.html.erb
    def index
        @instructors = Instructor.all
    end

    #Links to my  /instructors/:id route
    #links to a views/instructors/show.html.erb
    def show
        @instructor = Instructor.find(params[:id])
    end

    def new
        @instructor = Instructor.new
    end

    def create
        @instructor = Instructor.create(instructor_params)
        redirect_to '/instructors'
    end

    def edit
        @instructor = Instructor.find(params[:id])
    end

    def update
        @instructor = Instructor.find(params[:id])
        @instructor.update(instructor_params)
        redirect_to '/instructors'
    end

    def destroy
        Instructor.find(params[:id]).destroy
        redirect_to '/instructors'
    end

    private

    def instructor_params
        params.require(:instructor).permit(:first_name, :last_name, :age, :education, :email, :salary)
    end

end

app/controllers/members_controller.rb
class MembersController < ApplicationController
    before_action :authenticate_member!
    #Links to my /member route
    #links to a /views/member/index.html.erb
    def index
        @member = Member.all
        redirect_to '/admins/1'
    end

    #Links to my  /member/:id route
    #links to a views/member/show.html.erb
    def show
        @member = Member.find(params[:id])
        redirect_to '/admins/1'
    end

    def destroy
        @member = Member.find(params[:id])
        redirect_to '/members/sign_in'
    end
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :authenticate_member!
  def new
  end
  
  def create
    @member = member.find_by(email: params[:session][:email].downcase)
    if member && member.authenticate(params[:session][:password])
      # Log the user in and redirect to the user's show page.
    else
      # Create an error message.
      render 'new'
    end
  end

  def destroy
  end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
    before_action :authenticate_member!, :new_student_path, only: [:index, :create]
    respond_to :html, :js
    #Links to my /students route
    #links to a /views/students/index.html.erb
    def index
        @students = Student.all
    end

    #Links to my  /students/:id route
    #links to a views/students/show.html.erb
    def show
        @student = Student.find(params[:id])
    end


    def new
        @student = Student.new
    end

    def create
        @student = Student.create(student_params)
        redirect_to '/students'
    end


    def edit
        @student = Student.find(params[:id])
    end

    def update
        @student = Student.find(params[:id])
        @student.update(student_params)
        redirect_to '/students'
    end

    
    def destroy
        Student.find(params[:id]).destroy
        redirect_to '/students'
    end

    private

    def student_params
        params.require(:student).permit(:cohort_id, :first_name, :last_name, :age, :education, :email)
    end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cohorts_helper.rb
module CohortsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/cohorts/edit.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Students</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    </head>
    <body>
        <nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-3">
            <a class="navbar-brand col-sm-3 col-md-2 mr-5" href="#">New York Tech Academy</a>
            <ul class="navbar-nav px-5">
                <li class="nav-item text-nowrap">
                    <a class="nav-link" href="#"></a>
                </li>
            </ul>
        </nav>
<div class="container-fluid">
    <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-info sidebar">
          <div class="sidebar-sticky">
            <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
            </h6>
            <div class="list-group">
              <a href='/admins/1' class="list-group-item list-group-item-action active">
                Home
              </a>
              <a href='/cohorts' class="list-group-item list-group-item-action list-group-item-info">Cohorts</a>
              <a href='/courses' class="list-group-item list-group-item-action list-group-item-info">Courses</a>
              <a href='/instructors' class="list-group-item list-group-item-action list-group-item-info">Instructors</a>
              <a href='/students' class="list-group-item list-group-item-action list-group-item-info">Students</a>
            </div>
          </div>
        </nav>
        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
            <h1 class="h2 align-items-center">Edit Cohort Dashboard</h1>
            <hr>
            <div class="form-group"> 
                <%= form_for @cohort do |f| %>   
                    <%= f.label :name %>  
                    <%= f.text_field :name, value: @cohort.name %>
                    <hr>
                    <%= f.label :start_date %>  
                    <%= f.text_field :start_date, value: @cohort.start_date %>
                    <hr>
                    <%= f.label :end_date %>  
                    <%= f.text_field :end_date, value: @cohort.end_date %>
                    <hr> 
                    <%= f.label :course_id %>  
                    <%= f.number_field :course_id, value: @cohort.course_id %>
                    <hr>
                    <%= f.label :instructor_id %>  
                    <%= f.number_field :instructor_id, value: @cohort.instructor_id %>
                    <hr>                                        
                    <%= f.submit %>
                    <hr>
                <% end %>
                
                
                <%= button_to "Delete user", cohort_path(@cohort), remote: true, method: :delete %>
            </div>
 <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">          
           
            <div class="btn-toolbar mb-2 mb-md-0">
            </div>
          </div>

          <h2>Section title</h2>
        </main>
    </div>
</div>  
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>     
    </body>
</html>

app/views/cohorts/show.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Show Cohorts</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    </head>
    <body>
        <nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-3">
            <a class="navbar-brand col-sm-3 col-md-2 mr-5" href="#">New York Tech Academy</a>
            <ul class="navbar-nav px-5">
                <li class="nav-item text-nowrap">
                    <a class="nav-link" href="#"></a>
                </li>
            </ul>
        </nav>
        <div class="container-fluid">
            <div class="row">
                <nav class="col-md-2 d-none d-md-block bg-info sidebar">
                    <div class="sidebar-sticky">
                        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted"></h6>
                        <div class="list-group">
                            <a href='/admins/1' class="list-group-item list-group-item-action active">Home</a>
                            <a href='/cohorts' class="list-group-item list-group-item-action list-group-item-info">Cohorts</a>
                            <a href='/courses' class="list-group-item list-group-item-action list-group-item-info">Courses</a>
                            <a href='/instructors' class="list-group-item list-group-item-action list-group-item-info">Instructors</a>
                            <a href='/students' class="list-group-item list-group-item-action list-group-item-info">Students</a>
                        </div>
                    </div>
                </nav> 
            <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
            <h1 class="h2 align-items-center">Cohort Dashboard</h1>
            <hr>
            <table class="table">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">Cohort Name</th>
                        <th scope="col">Start Date</th>
                        <th scope="col">End Date</th>
                        <th scope="col">Course Name</th>
                        <th scope="col">Instructor Name</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <th scope="row"><%= @cohort.name %></th>
                        <td><%= @cohort.start_date %></td>
                        <td><%= @cohort.end_date %></td>
                        <td><%= @cohort.course.course_name %></td>
                        <td><%= @cohort.instructor.first_name %> <%= @cohort.instructor.last_name %> </td>
                    </tr>
                </tbody>
            </table>                              
            <div class="btn-toolbar mb-2 mb-md-0">
                <div class="btn-group mr-2">
                    <button class="btn btn-sm btn-warning"><a href='1/edit'>Edit</a></button>
                    <button class="btn btn-sm btn-danger"><%= link_to 'Delete', cohort_path(@cohort), remote: true, method: :delete %></button>
                </div>
                </div><hr>
                    <h2>Section title</h2>
                </div>
                </main>
            </div>
        </div>
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>     
    </body>
</html>

app/views/instructors/edit.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Students</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    </head>
    <body>
        <nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-3">
            <a class="navbar-brand col-sm-3 col-md-2 mr-5" href="#">New York Tech Academy</a>
            <ul class="navbar-nav px-5">
                <li class="nav-item text-nowrap">
                    <a class="nav-link" href="#"></a>
                </li>
            </ul>
        </nav>
<div class="container-fluid">
    <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-info sidebar">
          <div class="sidebar-sticky">
            <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
            </h6>
            <div class="list-group">
              <a href='/admins/1' class="list-group-item list-group-item-action active">
                Home
              </a>
              <a href='/cohorts' class="list-group-item list-group-item-action list-group-item-info">Cohorts</a>
              <a href='/courses' class="list-group-item list-group-item-action list-group-item-info">Courses</a>
              <a href='/instructors' class="list-group-item list-group-item-action list-group-item-info">Instructors</a>
              <a href='/students' class="list-group-item list-group-item-action list-group-item-info">Students</a>
            </div>
          </div>
        </nav>
        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
            <h1 class="h2 align-items-center">Edit Instructor Dashboard</h1>
            <hr>
            <div class="form-group"> 
                <%= form_for @instructor do |f| %>   
                    <%= f.label :first_name %>  
                    <%= f.text_field :first_name, value: @instructor.first_name %>
                    <hr>
                    <%= f.label :last_name %>  
                    <%= f.text_field :last_name, value: @instructor.last_name %>
                    <hr>
                    <%= f.label :age %>  
                    <%= f.number_field :age, value: @instructor.age %>
                    <hr> 
                    <%= f.label :education %>  
                    <%= f.text_field :education, value: @instructor.education %>
                    <hr>
                    <%= f.label :email %>  
                    <%= f.text_field :email, value: @instructor.email %>
                    <hr>
                    <%= f.label :salary %>  
                    <%= f.number_field :salary, value: @instructor.salary %>
                    <hr>                           
                    <%= f.submit %>
                    <hr>
                <% end %>

                <%= button_to 'Delete', instructor_path(@instructor), method: :delete %>
            </div>
            <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">          
           
            <div class="btn-toolbar mb-2 mb-md-0">
            </div>
            </div>

            <h2>Section title</h2>
        </main>
    </div>
</div>  
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>     
    </body>
</html>

app/views/instructors/show.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Show Instructors</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    </head>
    <body>
        <nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-3">
            <a class="navbar-brand col-sm-3 col-md-2 mr-5" href="#">New York Tech Academy</a>
            <ul class="navbar-nav px-5">
                <li class="nav-item text-nowrap">
                    <a class="nav-link" href="#"></a>
                </li>
            </ul>
        </nav>
<div class="container-fluid">
    <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-info sidebar">
          <div class="sidebar-sticky">
            <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
            </h6>
            <div class="list-group">
              <a href='/admins/1' class="list-group-item list-group-item-action active">
                Home
              </a>
              <a href='/cohorts' class="list-group-item list-group-item-action list-group-item-info">Cohorts</a>
              <a href='/courses' class="list-group-item list-group-item-action list-group-item-info">Courses</a>
              <a href='/instructors' class="list-group-item list-group-item-action list-group-item-info">Instructors</a>
              <a href='/students' class="list-group-item list-group-item-action list-group-item-info">Students</a>
            </div>
          </div>
        </nav>
        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
            <h1 class="h2 align-items-center">Instructor Dashboard</h1>
            <hr>
<table class="table">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">First Name</th>
                    <th scope="col">Last Name</th>
                    <th scope="col">Age</th>
                    <th scope="col">Education</th>
                    <th scope="col">Email</th>
                    <th scope="col">Salary</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <th scope="row"><%= @instructor.first_name %></th>
                    <td><%= @instructor.last_name %></td>
                    <td><%= @instructor.age %></td>
                    <td><%= @instructor.education %></td>
                    <td><%= @instructor.email %></td>
                    <td><%= @instructor.salary %></td>
                </tr>
            </tbody>
        </table>                              
            <div class="btn-toolbar mb-2 mb-md-0">
              <div class="btn-group mr-2">
                <button class="btn btn-sm btn-warning"><a href='1/edit'>Edit</a></button>
                <button class="btn btn-sm btn-danger"><%= link_to 'Delete', instructor_path(@instructor), remote: true, method: :delete %></button>
              </div>
            </div><hr>
            <h2>Section title</h2>
          </div>
        </main>
    </div>
</div>
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>     
    </body>
</html>

app/views/students/create.js.erb
$('#students').html("<%= j (render @students) %>");
$('#student-form').slideUp(350);

app/views/students/edit.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Students</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    </head>
    <body>
        <nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-3">
            <a class="navbar-brand col-sm-3 col-md-2 mr-5" href="#">New York Tech Academy</a>
            <ul class="navbar-nav px-5">
                <li class="nav-item text-nowrap">
                    <a class="nav-link" href="#"></a>
                </li>
            </ul>
        </nav>
<div class="container-fluid">
    <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-info sidebar">
          <div class="sidebar-sticky">
            <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
            </h6>
            <div class="list-group">
              <a href='/admins/1' class="list-group-item list-group-item-action active">
                Home
              </a>
              <a href='/cohorts' class="list-group-item list-group-item-action list-group-item-info">Cohorts</a>
              <a href='/courses' class="list-group-item list-group-item-action list-group-item-info">Courses</a>
              <a href='/instructors' class="list-group-item list-group-item-action list-group-item-info">Instructors</a>
              <a href='/students' class="list-group-item list-group-item-action list-group-item-info">Students</a>
            </div>
          </div>
        </nav>
        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
            <h1 class="h2 align-items-center">Edit Student Dashboard</h1>
            <hr>
            <div class="form-group"> 
                <%= form_for @student do |f| %>  
                    <%= f.label :cohort_id %>  
                    <%= f.number_field :cohort_id, value: @student.cohort_id %>
                    <hr>  
                    <%= f.label :first_name %>  
                    <%= f.text_field :first_name, value: @student.first_name %>
                    <hr>
                    <%= f.label :last_name %>  
                    <%= f.text_field :last_name, value: @student.last_name %>
                    <hr>
                    <%= f.label :age %>  
                    <%= f.number_field :age, value: @student.age %>
                    <hr> 
                    <%= f.label :education %>  
                    <%= f.text_field :education, value: @student.education %>
                    <hr>
                    <%= f.label :email %>  
                    <%= f.text_field :email, value: @student.email %>
                    <hr>               
                    <%= f.submit %>
                    <hr>
                <% end %>

                <%= button_to 'Delete', student_path(@student), method: :delete %>
                <hr>
            </div>
 <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">          
           
            <div class="btn-toolbar mb-2 mb-md-0">
            </div>
          </div>

          <h2>Section title</h2>
        </main>
    </div>
</div>  
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>     
    </body>
</html>

app/views/students/new.js.erb
$('#student-form').html("<%= j (render 'newForm') %>");
$('#student-form').slideDown(350);