config/routes.rb
Rails.application.routes.draw do
  get 'admins/index'
  devise_for :members
  get 'sessions/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'members#index'

  resources :cohorts
  resources :courses
  resources :instructors
  resources :students
  resources :admins 
  resources :members           
end

app/models/admin.rb
class Admin < ApplicationRecord      
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cohort.rb
class Cohort < ApplicationRecord
    has_many :students
    belongs_to :instructor, optional: true
    belongs_to :course, optional: true

    default_scope { order(:id) }
end

app/models/course.rb
class Course < ApplicationRecord
    has_many :cohorts

    default_scope { order(:id) }
end

app/models/instructor.rb
class Instructor < ApplicationRecord
    has_many :cohorts

    default_scope { order(:id) }
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/student.rb
class Student < ApplicationRecord
    belongs_to :cohort, optional: true

    default_scope { order(:id) }
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
    before_action :authenticate_member!
    #Links to my /admin route
    #links to a /views/admin/index.html.erb
    def index
        @admin = Admin.all
    end

    #Links to my  /admin/:id route
    #links to a views/admin/show.html.erb
    def show
        @admin = Admin.find(params[:id])
    end
end

app/controllers/cohorts_controller.rb
class CohortsController < ApplicationController
    before_action :authenticate_member!
    
    def index
        @cohorts = Cohort.all
    end

    def show
        @cohort = Cohort.find(params[:id])
    end


    def new
        @cohort = Cohort.new
    end

    def create
        @cohort = Cohort.create(cohort_params)
        redirect_to '/cohorts'
    end


    def edit
        @cohort = Cohort.find(params[:id])
    end

    def update
        @cohort = Cohort.find(params[:id])
        @cohort.update(cohort_params)
        redirect_to '/cohorts'
    end


    def destroy
        Cohort.find(params[:id]).destroy
        redirect_to '/cohorts'
    end

    private

    def cohort_params
        params.require(:cohort).permit(:name, :start_date, :end_date, :course_id, :instructor_id)
    end

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
    before_action :authenticate_member!
    #Links to my /courses route
    #links to a /views/courses/index.html.erb
    def index
        @courses = Course.all
    end

    #Links to my /courses/:id route
    #links to a views/courses/show.html.erb
    def show
        @course = Course.find(params[:id])
    end


    def new
        @course = Course.new
    end

    def create
        @course = Course.create(course_params)
        redirect_to '/courses'
    end


    def edit
        @course = Course.find(params[:id])
    end

    def update
        @course = Course.find(params[:id])
        @course.update(course_params)
        redirect_to '/courses'
    end

    def destroy
        Course.find(params[:id]).destroy
        redirect_to '/courses'
    end

    private

    def course_params
        params.require(:course).permit(:course_name)
    end

end

app/controllers/members_controller.rb
class MembersController < ApplicationController
    before_action :authenticate_member!
    #Links to my /member route
    #links to a /views/member/index.html.erb
    def index
        @member = Member.all
        redirect_to '/admins/1'
    end

    #Links to my  /member/:id route
    #links to a views/member/show.html.erb
    def show
        @member = Member.find(params[:id])
        redirect_to '/admins/1'
    end

    def destroy
        @member = Member.find(params[:id])
        redirect_to '/members/sign_in'
    end
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :authenticate_member!
  def new
  end
  
  def create
    @member = member.find_by(email: params[:session][:email].downcase)
    if member && member.authenticate(params[:session][:password])
      # Log the user in and redirect to the user's show page.
    else
      # Create an error message.
      render 'new'
    end
  end

  def destroy
  end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cohorts_helper.rb
module CohortsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/admins/index.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Cohorts</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
        <link rel="stylesheet" href="main.css">
    </head>
    <body class="text-center">
    <form class="form-signin">
      <img class="mb-4" src="https://getbootstrap.com/assets/brand/bootstrap-solid.svg" alt="" width="72" height="72">
      <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
      <label for="inputusername" class="sr-only">Email</label>
      <input type="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus>
      <label for="inputPassword" class="sr-only">Password</label>
      <input type="password" id="inputPassword" class="form-control" placeholder="Password" required>
      <div class="checkbox mb-3">
        <label>
          <input type="checkbox" value="remember-me"> Remember me
        </label>
      </div>
      <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
      <p class="mt-5 mb-3 text-muted">&copy; 2017-2018</p>
    </form>         
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>     
    </body>
</html> 

app/views/admins/show.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Admin Panel Home</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
        <link rel="stylesheet" href="application.css">
    </head>
    <body>
        <nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-3">
            <a class="navbar-brand col-sm-3 col-md-2 mr-5" href="#">New York Tech Academy</a>
            <input class="form-control form-control-dark w-25" type="text" placeholder="Search" aria-label="Search">
            <ul class="navbar-nav px-5">
                <li class="nav-item text-nowrap">
                    <a class="nav-link" href="#"></a>
                </li>
            </ul>
        </nav>
<div class="container-fluid">
    <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-info sidebar">
          <div class="sidebar-sticky">
            <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
            </h6>
            <div class="list-group">
              <a href='/admins/1' class="list-group-item list-group-item-action active">Home</a>
              <a href='/cohorts' class="list-group-item list-group-item-action list-group-item-info">Cohorts</a>
              <a href='/courses' class="list-group-item list-group-item-action list-group-item-info">Courses</a>
              <a href='/instructors' class="list-group-item list-group-item-action list-group-item-info">Instructors</a>
              <a href='/students' class="list-group-item list-group-item-action list-group-item-info">Students</a>
            </div>
          </div>
        </nav>
        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
            <h1 class="h2">Admin Dashboard</h1>
            <hr>
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">          
           
            <div class="btn-toolbar mb-2 mb-md-0">
              <div class="btn-group mr-2">
              </div>
            </div>
          </div>
          <h2>Section title</h2>
        </main>
    </div>
</div>
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>     
  </body>
</html>

app/views/layouts/_login.html.erb
<div> 
      <% if member_signed_in? %>
      <button>
      <%= link_to('Logout', destroy_member_session_path, method: :delete) %>        
      </button>
      <% else %>
      <button>
      <%= link_to('Login', new_member_session_path)  %>  
      </button>
      <% end %>

      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
</div> 

app/views/layouts/_newForm.html.erb
            <div class="form-group"> 
                <%= form_for @student, remote: true do |f| %> 
                    <%= f.label :cohort_id %>  
                    <%= f.number_field :cohort_id %>
                    <hr>  
                    <%= f.label :first_name %>  
                    <%= f.text_field :first_name %>
                    <hr>
                    <%= f.label :last_name %>  
                    <%= f.text_field :last_name %>
                    <hr>
                    <%= f.label :age %>  
                    <%= f.number_field :age %>
                    <hr> 
                    <%= f.label :education %>  
                    <%= f.text_field :education %>
                    <hr>
                    <%= f.label :email %> 
                    <%= f.text_field :email %>
                    <hr>               
                    <button type="submit" class="btn btn-sm btn-success"><%= f.submit %></button>
                <% end %>
                <hr>
            </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PamPanel</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= yield %>
    <%= render "layouts/login" %>    
  </body>
</html>